name: learn-github-actions
on: [push]
env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  Deploy-to-VPS:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh $SSH_USERNAME@$SSH_HOST -i ~/.ssh/id_rsa
          pwd
